service: servermenos

provider:
  name: aws
  runtime: nodejs6.10

functions:
  transformTransaction:
    handler: app.transformTransaction
    events:
      - http:
          path: payments
          method: post
